2020-12-21 11:01:00.007 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:01:00.002 [taskScheduler-3] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:01:00.020 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:01:00.023 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:02:00.003 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:02:00.002 [taskScheduler-9] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:02:00.003 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:02:00.004 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:03:00.001 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:03:00.001 [taskScheduler-3] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:03:00.002 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:03:00.003 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:04:00.003 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:04:00.004 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:04:00.003 [taskScheduler-1] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:04:00.005 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:05:00.002 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:05:00.004 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceFZImpl:171] - ----------没有连接到防灾服务器----------
2020-12-21 11:05:00.005 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:05:00.004 [taskScheduler-5] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:05:00.011 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:05:30.031 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:2338] - 查到维修计划条数0
2020-12-21 11:05:30.031 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:2368] - 跳出循环维修计划0  maplist0
2020-12-21 11:06:00.001 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:06:00.001 [taskScheduler-4] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:06:00.002 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:06:00.002 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:07:00.001 [taskScheduler-6] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:07:00.003 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:07:00.006 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:07:00.007 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:08:00.003 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:08:00.003 [taskScheduler-10] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:08:00.004 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:08:00.005 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:09:00.001 [taskScheduler-9] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:09:00.001 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:09:00.002 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:09:00.002 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:09:12.233 [Thread-25] ERROR [com.data.big.service.impl.ServiceImpl:1627] - ================连接工务服务失败====================
2020-12-21 11:09:12.233 [Thread-25] ERROR [com.data.big.service.impl.ServiceImpl:1628] - org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:163) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:129) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:82) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at javax.xml.ws.Service.<init>(Service.java:77) ~[?:1.8.0_191]
	at com.data.big.gw.GwaqscJxglService.<init>(GwaqscJxglService.java:49) ~[classes/:?]
	at com.data.big.service.impl.ServiceImpl.getportType(ServiceImpl.java:1620) [classes/:?]
	at com.data.big.util.MyThread.run(MyThread.java:32) [classes/:?]
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:87) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: javax.wsdl.WSDLException: WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl'.: java.net.ConnectException: Connection timed out: connect
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2198) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_191]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_191]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_191]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_191]
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2188) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
2020-12-21 11:10:00.004 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceFZImpl:171] - ----------没有连接到防灾服务器----------
2020-12-21 11:10:00.004 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:10:00.004 [taskScheduler-3] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:10:00.006 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:10:00.010 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:10:30.021 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:2338] - 查到维修计划条数0
2020-12-21 11:10:30.021 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:2368] - 跳出循环维修计划0  maplist0
2020-12-21 11:11:00.002 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:11:00.002 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:11:00.002 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:11:00.002 [taskScheduler-4] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:12:00.002 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:12:00.003 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:12:00.002 [taskScheduler-8] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:12:00.003 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:13:00.003 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:13:00.004 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:13:00.004 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:13:00.003 [taskScheduler-4] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:14:00.002 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:14:00.003 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:14:00.004 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:14:00.003 [taskScheduler-10] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:14:12.127 [Thread-27] ERROR [com.data.big.service.impl.ServiceImpl:1627] - ================连接工务服务失败====================
2020-12-21 11:14:12.127 [Thread-27] ERROR [com.data.big.service.impl.ServiceImpl:1628] - org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:163) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:129) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:82) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at javax.xml.ws.Service.<init>(Service.java:77) ~[?:1.8.0_191]
	at com.data.big.gw.GwaqscJxglService.<init>(GwaqscJxglService.java:49) ~[classes/:?]
	at com.data.big.service.impl.ServiceImpl.getportType(ServiceImpl.java:1620) [classes/:?]
	at com.data.big.util.MyThread.run(MyThread.java:32) [classes/:?]
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:87) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: javax.wsdl.WSDLException: WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl'.: java.net.ConnectException: Connection timed out: connect
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2198) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_191]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_191]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_191]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_191]
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2188) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
2020-12-21 11:15:00.002 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:15:00.005 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:15:00.005 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:15:00.005 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceFZImpl:171] - ----------没有连接到防灾服务器----------
2020-12-21 11:15:00.005 [taskScheduler-10] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:15:30.008 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:2338] - 查到维修计划条数0
2020-12-21 11:15:30.008 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:2368] - 跳出循环维修计划0  maplist0
2020-12-21 11:16:00.002 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:16:00.003 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:16:00.003 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:16:00.004 [taskScheduler-6] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:17:00.004 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:17:00.004 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:17:00.005 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:17:00.002 [taskScheduler-3] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:18:00.004 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:18:00.004 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:18:00.005 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:18:00.003 [taskScheduler-9] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:19:00.002 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:19:00.003 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:19:00.004 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:19:00.002 [taskScheduler-4] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:19:12.126 [Thread-29] ERROR [com.data.big.service.impl.ServiceImpl:1627] - ================连接工务服务失败====================
2020-12-21 11:19:12.126 [Thread-29] ERROR [com.data.big.service.impl.ServiceImpl:1628] - org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:163) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:129) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:82) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at javax.xml.ws.Service.<init>(Service.java:77) ~[?:1.8.0_191]
	at com.data.big.gw.GwaqscJxglService.<init>(GwaqscJxglService.java:49) ~[classes/:?]
	at com.data.big.service.impl.ServiceImpl.getportType(ServiceImpl.java:1620) [classes/:?]
	at com.data.big.util.MyThread.run(MyThread.java:32) [classes/:?]
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:87) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: javax.wsdl.WSDLException: WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl'.: java.net.ConnectException: Connection timed out: connect
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2198) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_191]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_191]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_191]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_191]
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2188) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
2020-12-21 11:20:00.004 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceFZImpl:171] - ----------没有连接到防灾服务器----------
2020-12-21 11:20:00.004 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:20:00.004 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:20:00.005 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:20:00.004 [taskScheduler-5] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:20:30.008 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:2338] - 查到维修计划条数0
2020-12-21 11:20:30.008 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:2368] - 跳出循环维修计划0  maplist0
2020-12-21 11:21:00.003 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:21:00.003 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:21:00.004 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:21:00.002 [taskScheduler-5] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:22:00.000 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:22:00.001 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:22:00.001 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:22:00.000 [taskScheduler-5] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:23:00.002 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:23:00.002 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:23:00.002 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:23:00.001 [taskScheduler-2] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:24:00.003 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:24:00.003 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:24:00.004 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:24:00.003 [taskScheduler-6] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:24:12.136 [Thread-31] ERROR [com.data.big.service.impl.ServiceImpl:1627] - ================连接工务服务失败====================
2020-12-21 11:24:12.136 [Thread-31] ERROR [com.data.big.service.impl.ServiceImpl:1628] - org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:163) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:129) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:82) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at javax.xml.ws.Service.<init>(Service.java:77) ~[?:1.8.0_191]
	at com.data.big.gw.GwaqscJxglService.<init>(GwaqscJxglService.java:49) ~[classes/:?]
	at com.data.big.service.impl.ServiceImpl.getportType(ServiceImpl.java:1620) [classes/:?]
	at com.data.big.util.MyThread.run(MyThread.java:32) [classes/:?]
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:87) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: javax.wsdl.WSDLException: WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl'.: java.net.ConnectException: Connection timed out: connect
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2198) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_191]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_191]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_191]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_191]
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2188) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
2020-12-21 11:25:00.003 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:25:00.003 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceFZImpl:171] - ----------没有连接到防灾服务器----------
2020-12-21 11:25:00.003 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:25:00.004 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:25:00.003 [taskScheduler-6] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:25:30.018 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:2338] - 查到维修计划条数0
2020-12-21 11:25:30.018 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:2368] - 跳出循环维修计划0  maplist0
2020-12-21 11:26:00.002 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:26:00.002 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:26:00.002 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:26:00.001 [taskScheduler-3] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:27:00.001 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:27:00.001 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:27:00.001 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:27:00.001 [taskScheduler-7] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:28:00.076 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:28:00.077 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:28:00.077 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:28:00.077 [taskScheduler-4] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:29:00.001 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:29:00.001 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:29:00.001 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:29:00.002 [taskScheduler-1] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:29:12.143 [Thread-33] ERROR [com.data.big.service.impl.ServiceImpl:1627] - ================连接工务服务失败====================
2020-12-21 11:29:12.143 [Thread-33] ERROR [com.data.big.service.impl.ServiceImpl:1628] - org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:163) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:129) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:82) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at javax.xml.ws.Service.<init>(Service.java:77) ~[?:1.8.0_191]
	at com.data.big.gw.GwaqscJxglService.<init>(GwaqscJxglService.java:49) ~[classes/:?]
	at com.data.big.service.impl.ServiceImpl.getportType(ServiceImpl.java:1620) [classes/:?]
	at com.data.big.util.MyThread.run(MyThread.java:32) [classes/:?]
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:87) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: javax.wsdl.WSDLException: WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl'.: java.net.ConnectException: Connection timed out: connect
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2198) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_191]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_191]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_191]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_191]
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2188) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
2020-12-21 11:30:00.000 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceFZImpl:171] - ----------没有连接到防灾服务器----------
2020-12-21 11:30:00.000 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:30:00.001 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:30:00.001 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:30:00.000 [taskScheduler-7] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:30:30.008 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:2338] - 查到维修计划条数0
2020-12-21 11:30:30.008 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:2368] - 跳出循环维修计划0  maplist0
2020-12-21 11:31:00.001 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:31:00.001 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:31:00.001 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:31:00.002 [taskScheduler-5] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:32:00.002 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:32:00.003 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:32:00.003 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:32:00.002 [taskScheduler-1] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:34:00.008 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:34:00.002 [taskScheduler-9] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:34:00.012 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:34:00.013 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:35:00.001 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:35:00.003 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:35:00.004 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:35:00.003 [taskScheduler-3] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:35:00.004 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceFZImpl:171] - ----------没有连接到防灾服务器----------
2020-12-21 11:36:00.009 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:36:00.005 [taskScheduler-3] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:36:00.014 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:36:00.015 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:37:00.002 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:37:00.002 [taskScheduler-2] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:37:00.002 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:37:00.003 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:38:00.003 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:38:00.003 [taskScheduler-1] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:38:00.004 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:38:00.005 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:39:00.004 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:39:00.004 [taskScheduler-2] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:39:00.005 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:39:00.006 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:40:00.002 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:40:00.002 [taskScheduler-3] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:40:00.002 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:40:00.003 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:40:00.005 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceFZImpl:171] - ----------没有连接到防灾服务器----------
2020-12-21 11:40:30.010 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:2338] - 查到维修计划条数0
2020-12-21 11:40:30.010 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:2368] - 跳出循环维修计划0  maplist0
2020-12-21 11:41:00.002 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:41:00.002 [taskScheduler-6] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:41:00.004 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:41:00.005 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:42:00.002 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:42:00.003 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:42:00.003 [taskScheduler-2] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:42:00.004 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:43:00.001 [taskScheduler-8] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:43:00.002 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:43:00.004 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:43:00.005 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:44:00.002 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 11:44:00.003 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 11:44:00.002 [taskScheduler-4] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 11:44:00.004 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 11:44:12.250 [Thread-22] ERROR [com.data.big.service.impl.ServiceImpl:1627] - ================连接工务服务失败====================
2020-12-21 11:44:12.251 [Thread-22] ERROR [com.data.big.service.impl.ServiceImpl:1628] - org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:163) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:129) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:82) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at javax.xml.ws.Service.<init>(Service.java:77) ~[?:1.8.0_191]
	at com.data.big.gw.GwaqscJxglService.<init>(GwaqscJxglService.java:49) ~[classes/:?]
	at com.data.big.service.impl.ServiceImpl.getportType(ServiceImpl.java:1620) [classes/:?]
	at com.data.big.util.MyThread.run(MyThread.java:32) [classes/:?]
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:87) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: javax.wsdl.WSDLException: WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl'.: java.net.ConnectException: Connection timed out: connect
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2198) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_191]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_191]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_191]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_191]
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2188) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
2020-12-21 15:00:30.065 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:2338] - 查到维修计划条数0
2020-12-21 15:00:30.066 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:2368] - 跳出循环维修计划0  maplist0
2020-12-21 15:01:00.006 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:01:00.010 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:01:00.010 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:01:00.002 [taskScheduler-5] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:02:00.001 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:02:00.001 [taskScheduler-9] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:02:00.001 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:02:00.002 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:03:00.001 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:03:00.001 [taskScheduler-7] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:03:00.003 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:03:00.004 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:04:00.001 [taskScheduler-7] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:04:00.002 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:04:00.003 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:04:00.003 [taskScheduler-6] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:05:00.001 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:05:00.002 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:05:00.002 [taskScheduler-4] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:05:00.002 [taskScheduler-8] ERROR [com.data.big.service.impl.ServiceFZImpl:171] - ----------没有连接到防灾服务器----------
2020-12-21 15:05:00.002 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:05:30.017 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:2338] - 查到维修计划条数0
2020-12-21 15:05:30.017 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:2368] - 跳出循环维修计划0  maplist0
2020-12-21 15:06:00.001 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:06:00.002 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:06:00.002 [taskScheduler-9] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:06:00.001 [taskScheduler-10] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:07:00.004 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:07:00.003 [taskScheduler-10] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:07:00.004 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:07:00.005 [taskScheduler-5] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:08:00.002 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:08:00.002 [taskScheduler-2] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:08:00.003 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:08:00.004 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:09:00.003 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:09:00.003 [taskScheduler-6] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:09:00.003 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:09:00.004 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:09:12.175 [Thread-23] ERROR [com.data.big.service.impl.ServiceImpl:1627] - ================连接工务服务失败====================
2020-12-21 15:09:12.175 [Thread-23] ERROR [com.data.big.service.impl.ServiceImpl:1628] - org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:163) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:129) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:82) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at javax.xml.ws.Service.<init>(Service.java:77) ~[?:1.8.0_191]
	at com.data.big.gw.GwaqscJxglService.<init>(GwaqscJxglService.java:49) ~[classes/:?]
	at com.data.big.service.impl.ServiceImpl.getportType(ServiceImpl.java:1620) [classes/:?]
	at com.data.big.util.MyThread.run(MyThread.java:32) [classes/:?]
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:87) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: javax.wsdl.WSDLException: WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl'.: java.net.ConnectException: Connection timed out: connect
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2198) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_191]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_191]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_191]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_191]
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2188) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
2020-12-21 15:10:00.002 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceFZImpl:171] - ----------没有连接到防灾服务器----------
2020-12-21 15:10:00.002 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:10:00.005 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:10:00.002 [taskScheduler-7] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:10:00.009 [taskScheduler-4] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:10:30.024 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:2338] - 查到维修计划条数0
2020-12-21 15:10:30.024 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:2368] - 跳出循环维修计划0  maplist0
2020-12-21 15:11:00.002 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:11:00.001 [taskScheduler-9] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:11:00.003 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:11:00.003 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:12:00.002 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:12:00.002 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:12:00.003 [taskScheduler-2] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:12:00.002 [taskScheduler-3] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:13:00.001 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:13:00.002 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:13:00.002 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:13:00.002 [taskScheduler-7] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:14:00.003 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:14:00.003 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:14:00.003 [taskScheduler-1] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:14:00.003 [taskScheduler-3] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:14:12.121 [Thread-25] ERROR [com.data.big.service.impl.ServiceImpl:1627] - ================连接工务服务失败====================
2020-12-21 15:14:12.122 [Thread-25] ERROR [com.data.big.service.impl.ServiceImpl:1628] - org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:163) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:129) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:82) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at javax.xml.ws.Service.<init>(Service.java:77) ~[?:1.8.0_191]
	at com.data.big.gw.GwaqscJxglService.<init>(GwaqscJxglService.java:49) ~[classes/:?]
	at com.data.big.service.impl.ServiceImpl.getportType(ServiceImpl.java:1620) [classes/:?]
	at com.data.big.util.MyThread.run(MyThread.java:32) [classes/:?]
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:87) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: javax.wsdl.WSDLException: WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl'.: java.net.ConnectException: Connection timed out: connect
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2198) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_191]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_191]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_191]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_191]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_191]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_191]
	at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(WSDLReaderImpl.java:2188) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2390) ~[wsdl4j-1.6.3.jar:1.6.3]
	at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(WSDLReaderImpl.java:2422) ~[wsdl4j-1.6.3.jar:1.6.3]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:266) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:165) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85) ~[cxf-rt-wsdl-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161) ~[cxf-rt-frontend-jaxws-3.2.4.jar:3.2.4]
	... 6 more
2020-12-21 15:15:00.001 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1680] - 连接工务服务失败
2020-12-21 15:15:00.001 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1783] - 连接工务服务失败
2020-12-21 15:15:00.001 [taskScheduler-7] ERROR [com.data.big.service.impl.ServiceImpl:1951] - 连接工务服务失败
2020-12-21 15:15:00.001 [taskScheduler-3] ERROR [com.data.big.service.impl.ServiceFZImpl:171] - ----------没有连接到防灾服务器----------
2020-12-21 15:15:00.006 [taskScheduler-6] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95] - Unexpected error occurred in scheduled task
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.data.big.task.TimingTask.getANBAO3(TimingTask.java:111) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2020-12-21 15:15:30.007 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:2338] - 查到维修计划条数0
2020-12-21 15:15:30.007 [taskScheduler-10] ERROR [com.data.big.service.impl.ServiceImpl:2368] - 跳出循环维修计划0  maplist0
